
#spring:
  #datasource:
   # url: jdbc:h2:mem:eartrainerDB
   # username: mastermusica
   # password:
 # jpa:
  #  open-in-view: false
   # hibernate:
    #  ddl-auto: update
#      hibernate:
#        format_sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        trace: false
#        web-allow-others: false